return {
  ASYNC = "async",
  BREAK = "break",
  CONST = "const",
  DO = "do",
  ENUM = "enum",
  EXPORT = "export",
  FN = "fn",
  FOR = "for",
  FOR_EACH = "for each",
  FROM = "from",
  IF = "if",
  NEXT = "next",
  PUB = "pub",
  RETURN = "return",
  TYPE = "type",
  USE = "use",
  VAR = "var",
  WHILE = "while",
  WITH = "with",
  YIELD = "yield"
}
